sudo: false
language: node_js
node_js:
  - stable
env:
  global:
    - BUILD_TIMEOUT=10000
    - NODE_ENV=production
install: npm install

deploy:
  provider: elasticbeanstalk
  access_key_id: AKIAIKAPGM6VB7OMQXOA
  secret_access_key:
    secure: RQlUkKVgCOL+JBaPiKVwzKCpo1mFZC678O+MJnIlPF/W8fqynOneJHXWJo1kBwRAZBMbtzOxEknHCS1+kqvhHJ0zESMwv/LdkJ8rlHQ4wgWhFZZ39HNNDiSnSQlT4+gL9Jex4vFodKqWy6VU8duCp0eCsgGt8/C0NhVj9XoHPJXt0RyV5uEOQuCo1WVg21+NjqPRnqQrYur/vXVEKgo9okIGV4+HMAS9vJSYQPQBL8/6LqryJDxtLLy2aM1vZBCGIagEJOR4XNpq0mfZey/goKIlSeLzLL3Gi0c15DfFgpDJoGv485HSIxw4ubC/GcUXGGpO93gtcShZFdNuyXlRCs9oRywjaM8hUoZVM0QzgOdCNZWXcyKEzDUpyZAGH3k4eSKHmcYdUiPXRUfv5J5b7UBXrj/kaVYQrSkZ7vpvu04CeaojWuj7arB1pZwZu2jqQ50tLiP74R5ou99Qq5fbPTz7atikO4+zQBHCKIrLxQ0idTL6HX+bJzyL0nRP43YoEZlBchCAbdD+K4koC985tLYTm7PfQSZrWZTWCKUbaAS48fGlkGY+3Oderf7vENR/wmSHvY4umGI/48w3lBONbBwcNrbEPc6h22i4GGosNiAEYtErIkxAgcOS8ISVVs8P6mdt6Hn1U7HvyX9rWu4TjRzvrVS93b2Sdj9BhLG3KcE=
  region: us-east-1
  app: packd
  env: packd-prod
  bucket_name: elasticbeanstalk-us-east-1-161663720085
  bucket_path: packd
  on:
    tags: true
